app.py
"""Registering the flask blueprints for the web app."""
import os
from flask import Flask
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

def create_app():
    """Factory for creating the app"""
    app = Flask(__name__)
    client = MongoClient(os.environ.get("MONGODB_URI"))
    app.db = client.get_default_database()
    
    app.register_blueprint(pages)
    return app

routes.py
"""Backend for the end points for the web app habit tracker"""
import datetime
import uuid
from collections import defaultdict
from flask import Blueprint, current_app, render_template, request, redirect, url_for

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")


@pages.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        dates = [start + datetime.timedelta(days=diff) for diff in range(-3,4)]
        return dates

    return {"date_range": date_range}

def today_at_midnight():
    """Takes todays date at midnight, which is 0 by default when creating new datetime object."""
    today = datetime.datetime.today()
    return datetime.datetime(today.year, today.month, today.day)

@pages.route("/")
def index():
    date_str = request.args.get("date")
    if date_str:
        selected_date = datetime.datetime.fromisoformat(date_str)
    else:
        selected_date = today_at_midnight()
    habits_on_date = current_app.db.habits.find({"added": {"$lte": selected_date}})
    completions = [
        habit["habit"]
        for habit in current_app.db.completions.find({"date": selected_date})
    ]

    return render_template(
        "index.html",
        habits=habits_on_date,
        selected_date=selected_date,
        completions=completions,
        title="Habit Tracker - Home",
        )

@pages.route("/add", methods=["GET", "POST"])
def add_habit():
    today = today_at_midnight()

    if request.method == "POST":
        current_app.db.habits.insert_one({"_id": uuid.uuid4().hex, "added": today, "name": request.form.get("habit")})
        
    return render_template("add_habit.html", title="Habit Tracker - Add Habit", selected_date=today,
)

@pages.route("/complete", methods=["POST"])
def complete():
    date_string = request.form.get("date")
    date = datetime.datetime.fromisoformat(date_string)
    habit = request.form.get("habitId")
    current_app.db.completions.insert_one({"date": date, "habit": habit})

    return redirect(url_for("habits.index", date=date_string))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}

<form class="form" method="POST">
    <textarea class="form__input" name="habit" id="habit" rows="3" placeholder="Add a new daily habit"></textarea>
    <button class="form__button" type="submit">Add</button>
</form>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="habit-list">
    {% for habit in habits %}
        {% set completed = habit["_id"] in completions %}
        {% if completed %}
            <div class="habit completed">
                <p class="habit__name">
                    {{ habit["name"] }}
                </p>
                <svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                </svg>
            </div>
        {% else %}
            <div class="habit">
                <form method="POST" class="habit__form" action="{{ url_for('habits.complete') }}">
                    <input type="hidden" name="habitId" value="{{ habit['_id'] }}" />
                    <input type="hidden" name="date" value="{{ selected_date }}" />
                    <button type="submit" class="habit__button">
                        {{ habit["name"] }}
                    </button>
                </form>
            </div>
        {% endif %}
    {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ title }}</title>
        <link rel="stylesheet" href=" {{ url_for('static', filename='css/main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>
    
    <body>
        <header class="header">
            <h1 class="header__logo"> <a href="{{ url_for('habits.index') }}" class="header__link">Habits</a></h1>
            {% if "add" not in request.endpoint %}
                <a href="{{ url_for('habits.add_habit') }}" class="header__link">+ Add new</a>
            {% endif %}
        </header>

        <main class="main">
            <section class="dates">
                {% for date in date_range(selected_date) %}
                <a 
                    class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else ''  }}"
                    href="{{ url_for('habits.index', date=date) }}">
                <time class="date" datetime="{{ date }}">
                    <span>{{ date.strftime("%a") }}</span>
                    <span>{{ date.strftime("%d") }}</span>
                </a>
                {% endfor %}
            </section>
            {% block main_content %}
            {% endblock %}
        </main>
    </body>
</html>